### ISSUE TITLE
Putting a blue panel in front of a blue background makes it hard to see

### ISSUE THREAD

**Issue by samreid** [phetsims/arithmetic#100]
Putting a blue panel in front of a blue background makes it hard to see.  Why not a different background color for the dialog?  see https://github.com/phetsims/arithmetic/issues/99 for screenshots

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
Assigning to @amanda-phet to decide if we should address and, if so, what colors to use instead.

**Comment by amanda-phet** [comment]
I agree that the blue panel does not make sense. I just looked at some other games and they also have the blue panel, so it's unfortunate that this sim color clashes with it. 

I'd like to try white, but that may be too harsh since it's a large panel. I will play around with some colors and get back to you.

**Comment by amanda-phet** [comment]
Let's make the background of that panel #ffebcd. 
![screen shot 2015-11-06 at 5 02 51 pm](https://cloud.githubusercontent.com/assets/7852916/11011706/3e1a0da4-84a8-11e5-8f17-f91b28d8490a.png)

**Comment by jbphet** [comment]
Updated to use #ffebcd as the background color, back to @amanda-phet for final approval.

**Comment by amanda-phet** [comment]
I think it looks good!
