### ISSUE TITLE
Score shows as 0

### ISSUE THREAD

**Issue by phet-steele** [phetsims/arithmetic#126]
During the animation to go back to the level select screen (the slide to the right animation), the score is displayed as 0. This shouldn't be a big issue since the score is still correct when returning to a level. Tested on Win 8.1 browsers in 1.0.0-dev.12. Seen in each game type, too.

Troubleshooting information:
Name: Arithmetic
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.12/arithmetic_en.html
Version: 1.0.0-dev.12
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by amanda-phet** [comment]
Just to clarify, do you mean you completed a level, hit back to return to the level selection screen, and the score shows as 0? But if you click on that level again you will see a completed board. 

This happened during an interview and it sounds like the same issue so I just want to be sure.

**Comment by amanda-phet** [comment]
I managed to capture a screenshot of this. When you click the back button you'll notice the upper right score incorrectly shows a 0. You have to be looking because the screen swipes over quickly!  
![screen shot 2015-01-28 at 12 04 50 pm](https://cloud.githubusercontent.com/assets/7852916/5944676/04a20f36-a6e6-11e4-848c-777359cadc4f.png)
But if you go back to your level, the score is still there.
![screen shot 2015-01-28 at 12 06 17 pm](https://cloud.githubusercontent.com/assets/7852916/5944684/14e10c12-a6e6-11e4-803b-be717fbd5ed1.png)

**Comment by jbphet** [comment]
I'll look at this and see if there is a reasonably easy fix, and will address it if so.

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
I removed the code that reset the level when returning to the level selection screen.  I think this is safe, since the level is then restored when going back to the level.  Appears to work on all screens.  Closing.
