### ISSUE TITLE
Stars reset after level completion and return to level

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/arithmetic#129]
Test device: Macbook pro and iPad2

Operating System: 10.10.1 and iOS8

Browser: Firefox and Safari

Problem description: When I complete a level and go back to level selection, then return to that level, my stars disappear. 

Steps to reproduce: See screenshots below

Severity:

Troubleshooting information (do not edit):
Name: Arithmetic
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.12/arithmetic_en.html
Version: 1.0.0-dev.12
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1147x601
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 16 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true

Steps to reproduce: 
Work on a level
![screen shot 2015-01-28 at 12 10 18 pm](https://cloud.githubusercontent.com/assets/7852916/5944801/03bd6b82-a6e7-11e4-95ce-35c372f9eb9d.png)
Go back to level selection, see progress
![screen shot 2015-01-28 at 12 10 24 pm](https://cloud.githubusercontent.com/assets/7852916/5944808/0c580054-a6e7-11e4-9c65-855f754a061e.png)
Finish level
![screen shot 2015-01-28 at 12 10 58 pm](https://cloud.githubusercontent.com/assets/7852916/5944811/12dfe93c-a6e7-11e4-940a-b775f73f5df6.png)
Click continue, go back to level selection, see your stars, then click that level again (instantaneously see the stars disappear) and the board is still completely filled in (issue #124 ?)
![screen shot 2015-01-28 at 12 11 08 pm](https://cloud.githubusercontent.com/assets/7852916/5944814/1a8e90a2-a6e7-11e4-9bfa-a35c3041f8b8.png)
Go back to level selection
![screen shot 2015-01-28 at 12 11 11 pm](https://cloud.githubusercontent.com/assets/7852916/5944833/4389ff46-a6e7-11e4-9cf9-93fe42b5e398.png)
Stars are gone :(

**Comment by jbphet** [comment]
Yep, this should be fixed.  Assigning to myself.

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
I discussed this with @amanda-phet and we decided to make the following changes:
+ when the level is completed and the dialog appears, pressing the "Continue" button will *not* take the user back to the level selection screen
+ when the user has completed a level, the board will be shown and they will be able to move back and forth between the table and the level selection screen without clearing the table
+ when displaying a completed table, the keypad and equation should not be visible
+ the user must press the refresh button in order to clear the completed table

**Comment by jbphet** [comment]
I've mostly implemented this for the "Multiply" screen, here's what's left to do:
+ Make it so that the equation and keypad don't reappear when showing a completed board and then returning to the level select button.  This should probably be done in conjunction with #126, since it also relates to a change in the view when pressing the button that returns the user to the level selection screen.
+ Implement for the Factor screen
+ Implement for the Divide screen

**Comment by jbphet** [comment]
This has now been implemented for the factor and divide screens, and the issue about keypad and equation visibility has also been addressed.

**Comment by jbphet** [comment]
Assigning to @amanda-phet for review of the behavioral changes.

**Comment by amanda-phet** [comment]
This seems to be a really nice behavior for the sim and is working really well. 

The only odd thing is that on the Factor screen the cursor shows a hand over the board, which makes me think something is click-able there (but that's not the case).

**Comment by jbphet** [comment]
I addressed @amanda-phet's last comment just above by adding code to make the board non-pickable (i.e. non-interactive) after the level is complete.  This can be tested on dev version http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.16/arithmetic_en.html.  Back to @amanda-phet for verification.

**Comment by amanda-phet** [comment]
Looks great to me! Closing.
