### ISSUE TITLE
Clicking multiple times on the "enter" key for a right answer

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/arithmetic#140]
To reproduce:
1. Go to the first screen
2. Select the first game level
3. Key in the right answer with the numbers
4. Rapidly press the "Enter"/"Return" key on the keypad. (it will ding multiple times)
5. After a delay, it will cycle through a bunch of other questions (one for each time you pressed the button).

Also sometime after this (future questions), you can repeatedly click "enter" with nothing happening except for the score going up:

![arithmetic-bug](https://cloud.githubusercontent.com/assets/480878/9374846/33be072c-46b7-11e5-9744-7cf6d95b7bf3.PNG)

As a side note, we should add a high-score dialog to this sim, so I can always be at the top from the bug!

**Comment by phet-steele** [comment]
I think I got you beat @jonathanolson.
https://github.com/phetsims/arithmetic/issues/122

I guess this is a problem again then.

**Comment by jbphet** [comment]
The enter key has been removed and the user now presses the "Check" button to submit an answer, see #130.  I tried pressing the "Check" button in the manner described above, but nothing bad happens since the button disappears as soon as the user presses it.  So, I believe this issue has been addressed.  Closing.
