### ISSUE TITLE
"Check" button not handled gracefully for stringTest=long

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/arithmetic#159]
The check button looks good for stringTest=double, but gets a bit whacky with a long string

Is there a way to preserve the button size and location?

![double](https://cloud.githubusercontent.com/assets/4051174/11787479/1df0e4da-a249-11e5-901c-59014b6db757.PNG)
![long](https://cloud.githubusercontent.com/assets/4051174/11787478/1dee72f4-a249-11e5-982b-9d44271417d0.PNG)

**Comment by jbphet** [comment]
What's going on here is that the button has a maxWidth setting, and is positioned based on its bottom edge, so long strings make it long and thin.  The position is technically being preserved in that the bottom edge is in the same location in each case.

I'll try adding a minHeight option for the button, and will use the standard Check button size when running on Win7+Chrome to define this size and see how it looks.

**Comment by jbphet** [comment]
Turns out that ```minHeight``` isn't supported for buttons, so I did the following:
- positioned the button based on a center location rather than the button edge
- changed the max width to be the space between the table and the edge of the layout bounds

This looks a bit better.  I think this is about as much effort as is justified, since it is very unlikely that long strings will be required here.  I tried translating the phrase "please try again" into German and using the result, and it looked fine.  Screenshot:

![arithmetic-button-2](https://cloud.githubusercontent.com/assets/3082831/11826787/952b1196-a344-11e5-984c-ba9a6006c8ad.png)

Here is what it looks like with the long string test:
![arithmetic-button-1](https://cloud.githubusercontent.com/assets/3082831/11826792/a79668ee-a344-11e5-9c9c-4e6749a45635.png)

**Comment by jbphet** [comment]
Assigning back to @ariel-phet to make sure he's cool with the result.

**Comment by ariel-phet** [comment]
@jbphet - yes this works for me...It just seemed like this is one of those strings that could actually go longer than the "double" mark, but this seems like a solution that should cover the bases. Closing.
