### ISSUE TITLE
No "ding" on factor screen if "try again" not pressed

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/arithmetic#160]
Appears to be a platform independent issue. (Seen on FF and Chrome)

To reproduce:
1. Have sound on
2. Go to factor screen
3. Get first try incorrect
4. Instead of pressing try again button, just move mouse/finger to the correct place on the board
5. When the correct answer is entered, no "ding" is given.

**Comment by amyh-phet** [comment]
The issue seems to be true for the sound for a second incorrect answer.

To reproduce:
1.  Have sound on.
2.  Go to factor screen
3.  Get first try incorrect
4.  Instead of pressing try again button, move mouse/finger to a second incorrect answer on board.
5.  When second incorrect answer is entered, no sound is given for incorrect answer.

**Comment by jbphet** [comment]
This should now be fixed.  The case described by @amyh-phet in the comment above about incorrect answers was actually a bit tricky to fix because there was no state transition in the game for this case.  In addition to making sure that the sound was produced during the state transitions, the code was modified so that the game would automatically move through the AWAITING_USER_INPUT state in the incorrect-to-incorrect case, and this seems to have resolved the issue.  This change required some modifications to the code that highlights the cells in order to cover all use cases.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to verify on v1.0.0-rc.2, available here: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-rc.2/arithmetic_en.html

**Comment by ariel-phet** [comment]
appears fixed, closing
