### ISSUE TITLE
best time is not shown on level-selection screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arithmetic#173]
This sim apparently keeps track of the best time for perfect scores (a little difficult to test because of #172). Why is the best time not shown under the buttons on the level-selection screen?  Keeping track of best time isn't very useful if you can't see what your best time was on the level-selection screen.  And other sims that track best time (search for 'bestTimeProperty') display it on the level-selection screen, so this is inconsistent.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to decide if this should be added.  I believe it would be fairly easy, but since it wasn't in the design I thought we should check.  He is welcome to assign to @amanda-phet if he'd like.  I'm also assuming that, even if fixed, this wouldn't warrant a maintenance release and would just go out the next time the sim is republished from the master branch.  This could potentially be a while, so we should be clear about that too.

#172 has been addressed, so it should be easier to test this if running from master.

**Comment by ariel-phet** [comment]
at developer meeting we discussed this being consistent, so yes it seems if the timer is on, and you get a perfect score best time should be displayed.

This is low priority, and can be done as a maintenance release sometime.

**Comment by marlitas** [comment]
It seems this might be straightforward and could be addressed in the upcoming region and character publication. Adding to the project board.

**Comment by amanda-phet** [comment]
I agree this can be addressed with the re-publication.

**Comment by marlitas** [comment]
We have decided to not show time on any LevelSelectionScreens moving forward.

**Comment by amanda-phet** [comment]
Discussed in https://github.com/phetsims/vegas/issues/51#issuecomment-1858343945 and we decided not to show times on level selection screens moving forward.

**Comment by marlitas** [comment]
Based on the meeting decision above, this issue can be closed.
