### ISSUE TITLE
Divide screen does not show "0" when it is entered

### ISSUE THREAD

**Issue by phet-steele** [phetsims/arithmetic#181]
1. Divide screen, any level.
2. Press "0"

From here notice two things:

- "0" did not appear in the input field of the equation
- The "Check" button has become enabled. You are allowed to submit this blank answer.

This is completely confusing, and incongruent with the Multiply screen. Multiply actually displays "0" when it is entered. The Divide screen should do the same and have the zero appear. The fact that you may submit this as an answer is totally fine.

**Comment by jbphet** [comment]
This was due to a test of the value zero that was being interpreted as "fasley".  This problem doesn't appear to exist on the currently published version, but the same code is in place, so I think this is probably because of some type changes to the values put into the equations.  I used the `isNaN` function so that this should work with number or strings.

Nice catch @phet-steele.  Can you test on master and see if this fix works and doesn't appear to cause any bad side effects?

**Comment by phet-steele** [comment]
Looks fine, thanks for your time!
