### ISSUE TITLE
Add in Africa/ Modest, Asia, Latin America, and Oceania character sets

### ISSUE THREAD

**Issue by marlitas** [phetsims/arithmetic#198]
This sim needs the initial structure to change character sets based on the region and culture preference.

**Comment by amanda-phet** [comment]
The original artwork is fairly high-res. It's also mipmaps. Can we discuss the ideal size to export this artwork at?

**Comment by amanda-phet** [comment]
Character sets are uploaded! 

The missing levels for Africa-Conservative should come from Africa, and the missing levels for Oceania should come from Asia.

**Comment by Luisav1** [comment]
All the character sets are loaded in now. @amanda-phet could you review to ensure it's all looking good? Thanks!

**Comment by amanda-phet** [comment]
1. There are a few PNGs I would like to update and will upload those today. 

2. The layout of the screen looks really odd- the text is lower and the buttons are smaller. I am mainly concerned about the interference of the text and buttons. 

Original: 
![image](https://github.com/phetsims/arithmetic/assets/7852916/9557f753-4a6b-49a3-9578-f4ce83fac316)

Current: 
![image](https://github.com/phetsims/arithmetic/assets/7852916/a97dc571-71ab-4593-8252-1631e4e9e1e7)

3. I'm also wondering if this sim should have a "multicultural" random option, since the USA version is all the same person. Can we randomly select from a different region for each screen?

**Comment by amanda-phet** [comment]
The SVGs are looking good to me and "multicultural" is working as expected.

**Comment by Luisav1** [comment]
Closing since the artwork is looking good. The layout issue with the texts being close to the buttons is being tracked here https://github.com/phetsims/vegas/issues/120.
