### ISSUE TITLE
Lost keyboard input after using screen recorder

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/arithmetic#219]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1056
When using the windows button + G to record the screen, the sim stops taking keyboard commands and does not start again until the page is refreshed. This did not occur the first time I recorded the page, but did the rest of the time, and I was unable to use the screen recorder and keyboard again.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Arithmetic‬
URL: https://phet-dev.colorado.edu/html/arithmetic/1.2.0-rc.1/phet/arithmetic_all_phet.html
Version: 1.2.0-rc.1 2024-03-20 22:03:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
I just saw this go by and it seems like something in scenery. Ill take a look too.

**Comment by jessegreenberg** [comment]
This was actually fixed in main today in https://github.com/phetsims/scenery/commit/122d1f42d5de1333553b9eaf94f1902eb461533f, but not in a way that can be easily cherry picked. 

We need to add the `blur` listener from that commit that was added to the window to clear the keystate when there is a loss of focus. In this case focus is lost because of the press of the windows key.

@Luisav1 can we meet to cherry-pick a change into arithmetic SHAs?

**Comment by jessegreenberg** [comment]
@Luisav1 and I put a partial fix in to a scenery branch and added the SHA to arithmetic 1.2 branch. It works when the browser loses focus in most cases. But it specifically does not work with using the Windows "Game Bar" because the browser does not get a blur event when that overlay opens.

I think we can fix that part by adding the meta key to 'KeyStateTracker.correctModifierKeys', I will work on that soon and we can cherry-pick that into arithmetic 1.2 SHAs.

**Comment by jessegreenberg** [comment]
OK, this has been fixed in main and in the arithmetic 1.2 scenery SHA. @Luisav1 over to you to verify if you want or to leave for the next RC.

**Comment by Luisav1** [comment]
Thanks @jessegreenberg, it's working great on main and in arithmetic 1.2. Leaving this open to be verified in the next RC test.

**Comment by KatieWoe** [comment]
Does look good in rc.2
