### ISSUE TITLE
Pointer changes to Hand when hovering over table border

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/arithmetic#224]
**Test device**
MacBook Air M1 chip + Chromebook

**Operating System**
14.4.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1056 and also seen in published, the mouse pointer changes to a hand when it hovers over the border of the table. 

**Steps to reproduce**
1. On any level on Screens 1 or 3, move the mouse to the outer border of the table.

**Visuals**
<img width="832" alt="Screenshot 2024-04-02 at 10 19 54 AM" src="https://github.com/phetsims/arithmetic/assets/87318828/5bba3bcb-3125-4344-82b2-da738521a166">

**Comment by Luisav1** [comment]
This occurred because there was a large white background rectangle on all tables, intended to maintain the cursor as a pointer when moving between cells. However, as each cell now autonomously sets its stroke to white, this rectangle appears vestigial and has been removed, eliminating the issue. Keeping this open for QA verification in the next RC.

**Comment by Luisav1** [comment]
This has been cherry-picked into Arithmetic 1.2 and is ready for review by QA.

**Comment by Nancy-Salpepi** [comment]
Looks fixed in 1.2.0-rc.2.
Closing.
